#!/usr/bin/env python

########################################
### must link this file to /bin/hmsh ###
########################################
import sys
sys.path.append("/maekin/lib/distro")

from shell import core

if __name__ == "__main__":
	core.start()

