#!/bin/bash
mkisofs -o c6maekin.iso -b isolinux.bin -c boot.cat -no-emul-boot \
-boot-load-size 4 -boot-info-table -R -J -v -T isolinux/
implantisomd5 c6maekin.iso
rm -f ../c6maekin.iso
mv c6maekin.iso ..
