MAEKIN_ROOT = "/maekin/"
MAEKIN_LIB_PATH = MAEKIN_ROOT + "lib/"
MAEKIN_VAR_PATH = MAEKIN_ROOT + "var/"

MONITOR_MODULE_PATH = "/maekin/lib/distro/"
MIDDLEWARE_PATH = MAEKIN_LIB_PATH + "middleware/"
LOG_PATH = "/var/log/"

HMM_MULTICAST_PORT = 5555
HMM_MULTICAST_ADDRESS = '224.0.0.1'
HMM_LISTENING_PORT = 5556	# contact by middleware

PRIVATE_NETWORK_ID = '10.1.0.0'
PRIVATE_NETWORK_IP = '10.1.0.1'
PRIVATE_PREFIX = '24'
PRIVATE_SUBNET = '255.255.255.0'
PRIVATE_RANGE = '10.1.0.2 10.1.0.254'
