#!/bin/bash
LOG_DIR=/var/log
ROOT_UID=0     # Only users with $UID 0 have root privileges.
LINES=50       # Default number of lines saved.
E_XCD=86       # Can't change directory?
E_NOTROOT=87   # Non-root exit error.
ARG0="other"

# Run as root, of course.
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "Must be root to run this script."
	exit $E_NOTROOT
fi 

if [ -n "$1" ]
then
	arg0=$1
fi

function init-maekin {
	echo "Building Maekin Directories Structure"
	mkdir -p /maekin/var/storage/templates
	mkdir -p /maekin/var/storage/shared
	
	echo "Adding Symbolic links"
	ln -f -s /maekin/lib/distro/init.d/mmond.py /etc/init.d/mmond
	ln -f -s /maekin/lib/distro/init.d/hmm.py /etc/init.d/hmm
	ln -f -s /maekin/lib/distro/shell/hmsh /sbin/hmsh
	ln -f -s /maekin/lib/distro/insertnode/insert-node /sbin/insert-node
	ln -f -s /maekin/lib/middleware/init.d/mklocd /etc/init.d/mklocd
	ln -f -s /maekin/lib/middleware/init.d/mklocm /etc/init.d/mklocm
	ln -f -s /maekin/lib/middleware/init.d/mkapi /etc/init.d/mkapi
	ln -f -s /maekin/lib/middleware/init.d/mkplanner /etc/init.d/mkplanner
	ln -f -s /maekin/lib/middleware/shell/mksh /sbin/mksh
	
	echo "Adjusting permission"
	chmod 744 /maekin/lib/distro/init.d/mmond.py
	chmod 744 /maekin/lib/distro/init.d/hmm.py
	chmod 744 /maekin/lib/distro/shell/hmsh
	chmod 744 /maekin/lib/distro/insertnode/insert-node
	chmod 744 /maekin/lib/middleware/init.d/mklocd
	chmod 744 /maekin/lib/middleware/init.d/mklocm 
	chmod 744 /maekin/lib/middleware/init.d/mkapi
	chmod 744 /maekin/lib/middleware/init.d/mkplanner
	chmod 744 /maekin/lib/middleware/shell/mksh
		
	echo "Auto Startup Maekin Service"
	chkconfig --add mmond
	chkconfig --add hmm
	chkconfig --add mklocm
	chkconfig --add mklocd
	
	echo "Shuting off NetworkManager service"
	chkconfig NetworkManager off
	service NetworkManager stop
	
	echo "Setting up network interface for KVM"
	# eth0
	echo DEVICE="eth0" > /etc/sysconfig/network-scripts/ifcfg-eth0
	echo NM_CONTROLLED="no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
	echo ONBOOT="yes" >> /etc/sysconfig/network-scripts/ifcfg-eth0
	echo BRIDGE="br0" >> /etc/sysconfig/network-scripts/ifcfg-eth0
	# bridge 0
	echo DEVICE="br0" > /etc/sysconfig/network-scripts/ifcfg-br0
	echo TYPE="bridge" >> /etc/sysconfig/network-scripts/ifcfg-eth0
	echo BOOTPROTO="dhcp" >> /etc/sysconfig/network-scripts/ifcfg-eth0
	echo ONBOOT="yes" >> /etc/sysconfig/network-scripts/ifcfg-eth0
	echo DELAY="0" >> /etc/sysconfig/network-scripts/ifcfg-eth0
	echo "Restarting network"
	service network restart
	
	echo "Creating DHCP configuration"
	echo "include \"/maekin/var/dhcp-distro.conf\"" > /etc/dhcp/dhcpd.conf;
	echo "include \"/maekin/var/dhcp-middleware.conf\"" >> /etc/dhcp/dhcpd.conf;
	touch /maekin/var/dhcp-middleware.conf
	touch /maekin/var/dhcp-middleware.conf
	
	echo "Adjusting libvirt config"
	mv /etc/sysconfig/libvirtd /etc/sysconfig/libvirtd.old
	sed s/#LIBVIRTD_ARGS/LIBVIRTD_ARGS/ </etc/sysconfig/libvirtd.old >/etc/sysconfig/libvirtd
	rm -f /etc/sysconfig/libvirtd.old
	
	echo "Adjusting SELinux"
	echo 0 > /selinux/enforce
	mv /etc/selinux/config /etc/selinux/config.old
	sed s/SELINUX=enforcing/SELINUX=permissive/ </etc/selinux/config.old >/etc/selinux/config
	rm -f /etc/selinux/config.old
}

function adjust-iptables {
	echo "Adjusting iptables"
	iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 2049 -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 50000 -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 5556 -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 16514 -j ACCEPT
	iptables -I INPUT 5 -p tcp -m state --state NEW -m tcp --dport 49152:49215 -j ACCEPT
	iptables -I INPUT 5 -p udp -m state --state NEW -m udp --dport 69 -j ACCEPT
	iptables -I INPUT 5 -p udp -m state --state NEW -m udp --dport 5555 -j ACCEPT
	service iptables save
	#service iptables restart
}

if [ "$arg0" = "help" ]; then
	echo Script for initialize Maekin setting 
	exit
elif [ "$arg0" = "init" ]; then
	init-maekin
	adjust-iptables
	exit
elif [ "$arg0" = "init-setting" ]; then
	init-maekin
	exit
elif [ "$arg0" = "adjust-iptables" ]; then
	adjust-iptables
	exit
else
	echo "Commands list"
	echo "    $0 init"
	echo "        doing all initialization and adjusting iptables rules for Maekin"
	echo "    $0 init-setting"
	echo "        initialize setting only"
	echo "    $0 adjust-iptables"
	echo "        adjust iptables rules only"
	exit
fi
