#!/usr/bin/env python
#
# mktaskd      This shell script takes care of starting and stopping
#              The Maekin Task Getter Daemon (mktaskd)
#
# chkconfig: 345 99 01
# description:  Maekin Task Getter Daemon.
# processname: mktaskd
# pidfile: /var/run/mktaskd.pid

import sys, time

#print sys.path

sys.path.append("/taskGetter")
import setting

from daemon.myDaemon import mktaskd

if __name__ == "__main__":
	#print "hello"
	#print sys.argv
	if len(sys.argv) >=2:
		if sys.argv[-1]=='debug':
			isDebugMode=True
		else:
			isDebugMode=False

		logFile=setting.LOG_PATH+'maekin.mktaskd'

		d = mktaskd('/var/run/mktaskd.pid',stdout=logFile,stderr=logFile,isDebugMode=isDebugMode)
		
		if 'start' == sys.argv[1]:
			d.waitLocalPort()
			d.start()
		elif 'stop' == sys.argv[1]:
			d.stop()
		elif 'restart' == sys.argv[1]:
			d.stop()
			d.waitLocalPort()
			d.start()
		elif 'status' == sys.argv[1]:
			d.status()
		elif 'clearlog' == sys.argv[1]:
			open(logFile,'w').close()
		else:
			print "Unknown command"
			sys.exit(2)
		sys.exit(0)
	else:
		print "usage: mktaskd {start|stop|restart|status|clearlog} [debug]"
		sys.exit(2)
