#!/bin/bash
#
# /etc/rc.d/init.d/mydaemon
#
# description: my first daemon script
#
# warning : can be edited on linux only
#

# Source function library.
. /etc/rc.d/init.d/functions

RUN_AS=mydaemon
MODULE_HOME=/root/middleware
SCRIPT_NAME=mydaemon.py
PYTHON_PATH=/usr/bin/python
PID_FILE=/var/run/mydaemon.pid
RETVAL=1

start()	{
		if [ ! -f /var/lock/subsys/mydaemon ]; then
			echo -n "Starting mydaemon services: ]"
			daemon --pidfile=$PID_FILE $PYTHON_PATH $MODULE_HOME/$SCRIPT_NAME
			RETVAL=$?
			[ $RETVAL -eq 0 ] && touch /var/lock/subsys/mydaemon
			echo
			return $RETVAL
		fi
		return 1
}

stop()	{
		echo -n $"Stopping mydaemon: "
		killproc -p $PID_FILE
		RETVAL=$?
		[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/mydaemon
		echo
		return $RETVAL
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	status)
		status
	;;
	*)
		echo "Usage: mydaemon {start|stop|status|restart}}"
		exit 1
	;;
esac
