#!/usr/bin/env python

import sys, time

#print sys.path
sys.path.append("/root/middleware")

from daemon.mydaemon import MyDaemon

if __name__ == "__main__":
	#print "hello"
	#print sys.argv
	d = MyDaemon('/var/run/mypyd.pid')
	if len(sys.argv) == 2:
		if 'start' == sys.argv[1]:
			d.start()
		elif 'stop' == sys.argv[1]:
			d.stop()
		elif 'restart' == sys.argv[1]:
			d.restart()
		else:
			print "Unknown command"
			sys.exit(2)
		sys.exit(0)
	else:
		print "usage: %s start|stop|restart" % sys.argv[0]
		sys.exit(2)
